---
image: registry.zammad.com/docker/zammad-ci:stable

workflow:
  rules:
    # Avoid duplicate branch and MR pipelines for push events to branches with an open MR.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    # Don't create branch pipelines for pushes to private branches (as there will also be a MR for them).
    - if: $CI_COMMIT_BRANCH =~ /^(private|cherry-pick-|renovate|dependabot)/ && $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always

stages:
  - pre
  - lint
  - screenshots
  - build
  - deploy

push to github:
  stage: pre
  before_script:
    - test -d $HOME/.ssh || mkdir $HOME/.ssh
    - ssh-keyscan github.com >> $HOME/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$PUSH_TO_GITHUB_SSH_PRIVATE_KEY" | ssh-add -
    - ssh-add -l
  script:
    - git fetch --unshallow
    - .gitlab/push_to_github.sh git@github.com:zammad/zammad-org.git
  only:
    - develop
    - stable

# This job will create commits in pipelines pushed from Weblate.
# It re-generates the catalog, and any additional files such as view templates and chat assets.
push translations update commit:
  stage: pre
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_MESSAGE =~ /Translations update from translations[.]zammad[.]org/
      when: always
    - when: never
  script:
    - pnpm install
    - pnpm i18n
    - git status
    - git config user.email "noreply@weblate.org"
    - git config user.name "Weblate"
    # Pushing via CI_JOB_TOKEN does not trigger another pipeline, so use a dedicated token.
    - git remote add gitlab_origin https://oauth2:${WEBLATE_ACCESS_TOKEN}@${CI_SERVER_FQDN}/${CI_PROJECT_PATH}.git
    - git add .
    - git status --porcelain | grep "^[MA]" || exit 0 # check if files were added/changed
    - 'git commit -m "Maintenance: Update translated files and catalog"'
    - git show --stat
    - git push gitlab_origin HEAD:$CI_COMMIT_REF_NAME

markdownlint:
  stage: lint
  image:
    name: davidanson/markdownlint-cli2:latest
    entrypoint: [""]
  script:
    - markdownlint-cli2 "src/en/**/*.md"

screenshots:
  stage: screenshots
  image: docker
  before_script:
    - .screenshots/zammad-stack/start.sh
    - docker ps
  script:
    - .screenshots/zammad-stack/screenshots.sh
    - test -d src/public/screenshots/cypress # check that screenshots were copied from the container
  after_script:
    - .screenshots/zammad-stack/stop.sh
    - docker ps
  artifacts:
    name: screenshots
    expose_as: "Generated Screenshots"
    expire_in: 1 week
    paths:
      - src/public/screenshots/cypress

build:
  stage: build
  script:
    - pnpm install
    - pnpm build
  artifacts:
    name: static-html
    expose_as: "Generated Website HTML"
    expire_in: 1 week
    paths:
      - dist

deploy to website:
  stage: deploy
  script:
    - test -d $HOME/.ssh || mkdir $HOME/.ssh
    - ssh-keyscan -p $DEPLOYPORT $DEPLOYHOST_COMMUNITY >> $HOME/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_COMMUNITY")
    - ls -al
    - apt update && apt install -y --no-install-recommends rsync
    - rsync -avz --delete -e "ssh -p $DEPLOYPORT" dist/ $DEPLOYUSER_COMMUNITY@$DEPLOYHOST_COMMUNITY:/home/next.zammad.org/pub/
    - ssh $DEPLOYUSER_COMMUNITY@$DEPLOYHOST_COMMUNITY -tt "sudo systemctl reload nginx"
  only:
    - develop
