---
image: registry.zammad.com/docker/zammad-ruby:stable

stages:
  - lint
  - test

'push to github':
  stage: lint
  before_script:
    - test -d $HOME/.ssh || mkdir $HOME/.ssh
    - ssh-keyscan github.com >> $HOME/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$PUSH_TO_GITHUB_SSH_PRIVATE_KEY" | ssh-add -
    - ssh-add -l
  script:
    - git fetch --unshallow
    - .gitlab/push_to_github.sh git@github.com:zammad/zammad-org.git
  only:
    - develop
    - stable

super linter:
  stage: lint
  image:
    name: github/super-linter:v5
    entrypoint: [""]
  variables:
    FILTER_REGEX_EXCLUDE: doc/.vitepress|pnpm-lock.yaml
  script:
    - |
      if [[ "${CI_DEBUG_TRACE,,}" == "true" || "${CI_COMPONENT_TRACE,,}" == "true" ]]; then
        echo "CI Component Trace (I_COMPONENT_TRACE) or GitLab's global trace (CI_DEBUG_TRACE) has been set, debug logging. More info: https://docs.gitlab.com/ee/ci/variables/#enable-debug-logging"
        set -xv
        SL_LOG_LEVEL="TRACE"
      fi
      export DISABLE_ERRORS=true #must be set in order to collect output file.
      export RUN_LOCAL="true"
      export DEFAULT_WORKSPACE=${CI_PROJECT_DIR}
      export ANSIBLE_DIRECTORY=$CI_PROJECT_PATH
      export LINTER_RULES_PATH=$CI_PROJECT_PATH/.github/linters
      export CREATE_LOG_FILE=true
      export LOG_FILE=super-linter.log
      echo "Running super-linter"
      LOG_LEVEL=VERBOSE /action/lib/linter.sh
  artifacts:
    expose_as: 'Super Linter Test Results'
    paths: ['super-linter.log']


'build and deploy':
  stage: test
  script:
    - pnpm add -D vitepress
    - pnpm build
    - test -d $HOME/.ssh || mkdir $HOME/.ssh
    - ssh-keyscan -p $DEPLOYPORT $DEPLOYHOST_COMMUNITY >> $HOME/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY_COMMUNITY")
    - ls -al
    - apt update && apt install -y --no-install-recommends rsync
    - rsync -avz --delete -e "ssh -p $DEPLOYPORT" ./doc/.vitepress/dist/ $DEPLOYUSER_COMMUNITY@$DEPLOYHOST_COMMUNITY:/home/next.zammad.org/pub/
  only:
    - develop
