describe('Rails commands screenshots', () => {
      it('article creation note', () => {
      cy.visit('/desktop/login')
      cy.loginDesktopView(Cypress.env('ADMIN_LOGIN'), Cypress.env('ADMIN_PASS'))
      cy.visit('/desktop/tickets/5')
      cy.get('main').should('exist')
      cy.get('button').contains('Add internal note').click()
      cy.wait(1000)
      cy.get('[id^=internal-]').first().click().wait(200)
      cy.get('[role="textbox"]').type('This is an article text...')
      cy.get('[id="ticketArticleReplyForm"]').screenshot('article-creation-note', { padding: 5 })
      cy.get('button').contains('Discard your unsaved changes').click()
      cy.get('button').contains('Discard changes').click()
      })
    })