map_hash_bucket_size 256; # see http://nginx.org/en/docs/hash.html

map $request_uri $redirect_uri_301  {
    include /etc/nginx/redirect_uri_301.map;
}

map $request_uri $redirect_uri_302  {
    include /etc/nginx/redirect_uri_302.map;
}

server {
    # https://vitepress.dev/guide/deploy#nginx
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    listen 80;
    server_name _;
    index index.html;

    location / {
        # content location
        root /app;

        # exact matches -> reverse clean urls -> folders -> not found
        try_files $uri $uri.html $uri/ =404;

        # non existent pages
        error_page 404 /404.html;

        # a folder without index.html raises 403 in this setup
        error_page 403 /404.html;

        # adjust caching headers
        # files in the assets folder have hashes filenames
        location ~* ^/assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }

    if ($redirect_uri_301) {
        return 301 $redirect_uri_301;
    }

    if ($redirect_uri_302) {
        return 302 $redirect_uri_302;
    }
}
