#!/bin/bash

set -e

echo "Updating .po4a.conf…"

# shellcheck disable=SC2155
export SOURCES=$(find doc/en -name "*.md" | sort | sed "s#doc/en/##; s#\(.*\)#[type: md] doc/en/\1 \$lang:doc/\$lang/\1#")

perl -i -p0e 's/# Content files.*/# Content files (autogenerated by .gitlab\/update_po4a_conf.sh)\n$ENV{SOURCES}\n/s' .po4a.conf