#!/bin/bash

set -e

echo "Updating .po4a.conf…"

# shellcheck disable=SC2155
export SOURCES=$(find src/en -name "*.md" | sort | sed "s#src/en/##; s#\(.*\)#[type: md] src/en/\1 \$lang:src/\$lang/\1#")

perl -i -p0e 's/# Content files.*/# Content files (autogenerated by .gitlab\/update_po4a_conf.sh)\n$ENV{SOURCES}\n/s' .po4a.conf