---
themeConfig:
  docFooter:
    next: 'Следећа страна'
    prev: 'Претходна страна'
  footer:
    copyright: 'Copyright © 2012-садашњост <a href="https://zammad-foundation.org">Zammad фондација</a>'
    items:
      - 
        link: /sr/imprint
        text: Импресум
      - 
        link: /sr/gdpr
        text: 'Политика приватности'
    message: 'Zammad Hub'
  lastUpdated:
    text: 'Освежено у'
  nav:
    - 
      link: https://www.zammad.com
      text: Zammad.com
    - 
      link: https://community.zammad.org/
      text: 'Форум онлајн заједнице'
    - 
      activeMatch: .*
      items:
        - 
          activeMatch: .*
          link: /
          noIcon: true
          target: _self
          text: 'Следеће издање'
        - 
          link: https://zammad.org
          noIcon: true
          target: _self
          text: 'Актуелно издање'
      text: 'Следеће издање'
  outline:
    label: 'На овој страни'
  socialLinks:
    - 
      icon: github
      link: https://github.com/zammad
