---
themeConfig:
  docFooter:
    next: 'Próxima página'
    prev: 'Página anterior'
  footer:
    copyright: 'Copyright © 2012-presente <a href="https://zammad-foundation.org">Zammad Foundation</a>'
    items:
      - 
        link: /pt_BR/imprint
        text: 'Aviso legal'
      - 
        link: /pt_BR/gdpr
        text: 'Política de privacidade'
    message: 'Zammad Hub'
  header:
    link: https://github.com/zammad/zammad-org/issues
    text: '🛠️ Esta documentação ainda está em construção, por favor relate quaisquer problemas.'
  lastUpdated:
    text: 'Atualizado em'
  nav:
    - 
      link: https://www.zammad.com
      text: Zammad.com
    - 
      link: https://community.zammad.org/
      text: 'Fórum da comunidade'
    - 
      activeMatch: .*
      items:
        - 
          activeMatch: .*
          link: /
          noIcon: true
          target: _self
          text: 'Próxima versão'
        - 
          link: https://zammad.org
          noIcon: true
          target: _self
          text: 'Versão atual'
      text: 'Próxima versão'
  notFound:
    code: 404
    linkLabel: 'ir para a página inicial'
    linkText: 'Me leve para a página inicial'
    quote: 'Mas se você não mudar de direção, e continuar procurando, pode acabar chegando aonde está indo.'
    title: 'PÁGINA NÃO ENCONTRADA'
  outline:
    label: 'Nesta página'
    level:
      - '2'
      - '4'
  socialLinks:
    - 
      icon: github
      link: https://github.com/zammad
  user:
    rootGroupText: 'Use Zammad'
