---
themeConfig:
  nav:
    - text: 'Zammad.com'
      link: 'https://www.zammad.com'
    - text: 'Community forum'
      link: 'https://community.zammad.org/'
    - text: Next release
      activeMatch: .*
      items:
        - text: Next release
          link: /
          target: _self
          noIcon: true
          activeMatch: .*
        - text: Current release
          link: https://zammad.org
          target: _self
          noIcon: true
  sidebar:
    - text: Get Started
      items:
        - text: Get Zammad
          link: /en/get-zammad/get-started
        - text: Install Zammad
          link: /en/get-zammad/installation
    - text: Documentation
      link: /en/doc-start
      items:
        - text: Use Zammad
          collapsed: false
          items:
            - text: General
              link: /en/use/general/index
            - text: How to
              link: /en/use/how-to/index
            - text: FAQs
              link: /en/use/faq/index
        - text: Administrate Zammad
          collapsed: true
          items:
            - text: Setup a new system
              link: /en/administrate/setup
            - text: Manage channels
              link: /en/administrate/manage-channels
    - text: Contribute
      items:
        - text: Contribute
          link: /en/contribute/contribute
        - text: Style and content guide
          link: /en/contribute/style-guide
    - text: Reference
      items:
        - text: Glossary
          link: /en/reference/glossary
        - text: API reference
          link: /en/reference/api-reference
        - text: Rails commands
          link: /en/reference/rails-commands
  outline:
    label: 'On this page'
  footer:
    items:
      - text: Imprint
        link: /en/imprint
      - text: Privacy policy
        link: /en/gdpr
    message: 'Zammad Hub'
    copyright: Copyright © 2012-present <a href="https://zammad-foundation.org">Zammad Foundation</a>
  socialLinks:
    - icon: 'github'
      link: 'https://github.com/zammad'
  lastUpdated:
    text: 'Updated at'
  docFooter:
    prev: 'Next page'
    next: 'Previous page'
