---
themeConfig:
  docFooter:
    next: 'Nächste Seite'
    prev: 'Vorige Seite'
  footer:
    copyright: 'Copyright © 2012-present <a href="https://zammad-foundation.org">Zammad Foundation</a>'
    items:
      - 
        link: /imprint
        text: Imprint
      - 
        link: /gdpr
        text: 'Privacy policy'
    message: 'Zammad Hub'
  lastUpdated:
    text: 'Aktualisiert am'
  nav:
    - 
      link: https://www.zammad.com/de
      text: Zammad.com
    - 
      link: https://community.zammad.org/
      text: Community-Forum
    - 
      activeMatch: .*
      items:
        - 
          activeMatch: .*
          link: /
          noIcon: true
          target: _self
          text: 'Nächste Version'
        - 
          link: https://zammad.org
          noIcon: true
          target: _self
          text: 'Aktuelle Version'
      text: 'Nächste Version'
  outline:
    label: 'Auf dieser Seite'
  sidebar:
    - 
      items:
        - 
          items:
            - 
              link: get-started/start
              text: Start
            - 
              link: get-started/deployment
              text: 'Zammad in Betrieb nehmen'
          text: 'Zammad holen'
      text: 'Mit Zammad loslegen'
    - 
      items:
        - 
          collapsed: true
          items:
            - 
              link: /documentation/user-docs/index
              text: Anmelden
            - 
              link: /documentation/user-docs/index
              text: Ticket-Bearbeitung
          text: 'Zammad verwenden'
        - 
          collapsed: true
          items:
            - 
              link: /documentation/user-docs/index
              text: 'Allgemeine Einstellungen'
            - 
              link: /documentation/user-docs/index
              text: Benutzerverwaltung
          text: 'Zammad administrieren'
      text: Dokumentation
    - 
      items:
        - 
          link: contribute/style-guide
          text: 'Leitfaden für Stil und Inhalt'
        - 
          link: contribute/contribute
          text: Beitrag
      text: Beitragen
    - 
      items:
        - 
          link: reference/glossary
          text: Glossar
        - 
          link: reference/api-reference
          text: API-Referenz
        - 
          link: reference/rails-commands
          text: Rails-Befehle
      text: Referenz
    - 
      items:
        - 
          link: /documentation/admin-docs/index
          text: Administrations-Dokumentation
        - 
          link: /cheat-sheet
          text: 'Spickzettel für die Formatierung'
      text: 'Spielplatz (Beispielinhalt)'
  socialLinks:
    - 
      icon: github
      link: https://github.com/zammad
