---
themeConfig:
  docFooter:
    next: 'Pagina successiva'
    prev: 'Pagina precedente'
  footer:
    copyright: 'Copyright © 2012-ad oggi <a href="https://zammad-foundation.org">Zammad Foundation</a>'
    items:
      - 
        link: /en/imprint
        text: Imprint
      - 
        link: /it/gdpr
        text: 'Informativa sulla privacy'
    message: 'Zammad Hub'
  header:
    link: https://github.com/zammad/zammad-org/issues
    text: '🛠️ Questa documentazione è ancora in fase di elaborazione, vi preghiamo di segnalare eventuali problemi.'
  lastUpdated:
    text: 'Aggiornato il'
  nav:
    - 
      link: https://www.zammad.com
      text: Zammad.com
    - 
      link: https://community.zammad.org/
      text: 'Community forum'
    - 
      activeMatch: .*
      items:
        - 
          activeMatch: .*
          link: /
          noIcon: true
          target: _self
          text: 'Next release'
        - 
          link: https://zammad.org
          noIcon: true
          target: _self
          text: 'Versione attuale'
      text: 'Next release'
  notFound:
    code: 404
    linkLabel: 'vai alla homepage'
    linkText: 'Take me home'
    quote: 'Ma se non cambi direzione, e se continui a cercare, potresti finire esattamente dove stai andando.'
    title: 'PAGINA NON TROVATA'
  outline:
    label: 'In questa pagina'
    level:
      - '2'
      - '4'
  socialLinks:
    - 
      icon: github
      link: https://github.com/zammad
  user:
    rootGroupText: 'Use Zammad'
