---
themeConfig:
  docFooter:
    next: 'Претходна страна'
    prev: 'Следећа страна'
  footer:
    copyright: 'Copyright © 2012-садашњост <a href="https://zammad-foundation.org">Zammad фондација</a>'
    items:
      - 
        link: /en/imprint
        text: Импресум
      - 
        link: /en/gdpr
        text: 'Политика приватности'
    message: 'Zammad чвориште'
  lastUpdated:
    text: 'Освежено у'
  nav:
    - 
      link: https://www.zammad.com
      text: Zammad.com
    - 
      link: https://community.zammad.org/
      text: 'Форум онлајн заједнице'
    - 
      activeMatch: .*
      items:
        - 
          activeMatch: .*
          link: /
          noIcon: true
          target: _self
          text: 'Следеће издање'
        - 
          link: https://zammad.org
          noIcon: true
          target: _self
          text: 'Актуелно издање'
      text: 'Следеће издање'
  outline:
    label: 'На овој страни'
  sidebar:
    - 
      items:
        - 
          link: /en/get-zammad/get-started
          text: 'Преузмите Zammad'
        - 
          link: /en/get-zammad/installation
          text: 'Инсталација Zammad-а'
      text: 'Први кораци'
    - 
      items:
        - 
          collapsed: false
          items:
            - 
              link: /en/use/general/index
              text: Уопштено
            - 
              link: /en/use/how-to/index
              text: 'Како да'
            - 
              link: /en/use/faq/index
              text: FAQ
          text: 'Коришћење Zammad-а'
        - 
          collapsed: true
          items:
            - 
              link: /en/administrate/setup
              text: 'Подешавање новог система'
            - 
              link: /en/administrate/manage-channels
              text: 'Управљање каналима'
          text: 'Zammad администрација'
      link: /en/doc-start
      text: Документација
    - 
      items:
        - 
          link: /en/contribute/contribute
          text: Учествујте
        - 
          link: /en/contribute/style-guide
          text: 'Водич кроз стил и садржај'
      text: Учествујте
    - 
      items:
        - 
          link: /en/reference/glossary
          text: Речник
        - 
          link: /en/reference/api-reference
          text: 'API референца'
        - 
          link: /en/reference/rails-commands
          text: 'Rails команде'
      text: Референца
  socialLinks:
    - 
      icon: github
      link: https://github.com/zammad
