name: CI

on:
  pull_request:
  # TODO: Drop
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        globs: src/en/**/*.md
  screenshots:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_REF_NAME: ${{github.ref_name}}
      CI_JOB_ID: ${{github.job}}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: zammad/zammad-docker-compose
        path: zammad-docker-compose
    - run: .screenshots/zammad-stack/start.sh
    - run: |
        .screenshots/zammad-stack/screenshots.sh || true # TODO drop this, first run always fails?
        .screenshots/zammad-stack/screenshots.sh
        test -d src/public/screenshots/cypress # check that screenshots were copied from the container
    - run: .screenshots/zammad-stack/stop.sh
    - id: sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v4
      with:
        name: screenshots-${{ steps.sha.outputs.sha_short }}
        path: src/public/screenshots/cypress
