name: CI

on:
  pull_request:
  # TODO: Drop
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        globs: src/en/**/*.md
